# Site settings

title: "QC International Pink Film Festival 2016"
baseurl: http://toffmendoza.me/sandbox-qcpinkfest
#baseurl: http://qcpinkfest.com

# Build settings
markdown: kramdown
permalink: pretty

# Site variables


itemsNavbarLeft:
 - id: "about"
   name: "About"
   url: "/about"
 - id: "program"
   name: "Program"
   url: "/program"
   sub:
    - id: "opening"
      name: "Opening"
      url: "/opening"
    - id: "keps"
      name: "Keps"
      url: "/keps"
 - id: "films"
   name: "Films"
   url: "/films"
   sub:
    - id: "tickets"
      name: "Tickets"
      url: "/tickets"
    - id: "schedule"
      name: "Schedule"
      url: "/schedule"
itemsNavbarRight:
 - id: "news"
   name: "News"
   url: "/news"
 - id: "contact"
   name: "Contact"
   url: "/contact"
 - id: "archive"
   name: "Archive"
   url: "/archive"
   sub:
    - id: "2015"
      name: "2015"
      url: "/2015"
    - id: "2014"
      name: "2014"
      url: "/2014"


itemsSponsors:
 - id: ""
   name: ""
   logo: ""
 - id: ""
   name: ""
   logo: ""
 - id: ""
   name: ""
   logo: ""


urlOfficial: "http://qcpinkfest.com/"
urlFacebook: "https://www.facebook.com/qcpinkfest/"
#urlTwitter: "https://twitter.com/y4it"
#urlInstagram: "https://www.instagram.com/y4it/"
#urlYouTube: "https://www.youtube.com/user/iloveY4iT"
#urlSnapchat: "https://www.snapchat.com/add/y4it"
#urlViber: "http://chats.viber.com/y4it"
