# Site settings

title: "UP Business Administration Council"
baseurl: http://toffmendoza.me/sandbox-bac
#baseurl: http://

# Build settings
markdown: kramdown
permalink: pretty

# Site variables
switchPanels: true

itemsNavbarLeft:
 - id: "about"
   name: "About Us"
   url: "/about" #url: "/about"
   lines: 1
   sub:
    - id: "vision_mission"
      name: "Vision and Mission"
      url: "/vision_mission"
    - id: "slogan_thrusts"
      name: "Slogan and Thrusts"
      url: "/slogan_thrusts"
    - id: "constitution"
      name: "Constitution"
      url: "/constitution"
    - id: "members"
      name: "BAC Members"
      url: "/members"
    - id: "edge"
      name: "EDGE Program"
      url: "/edge"
    - id: "fin_statements"
      name: "Financial Statements"
      url: "/fin_statements"
 - id: "news"
   name: "News & Announcements"
   url: "/news" #url: "/program"
   lines: 2
   nameDisplay:
    - "News &"
    - "Announcements"
 - id: "events"
   name: "Projects & Events"
   url: "/events"
   lines: 2
   nameDisplay:
    - "Projects &"
    - "Events"
itemsNavbarRight:
 - id: "services"
   name: "Services"
   url: "/services" #url: "/news"
   lines: 1
   sub:
    - id: "opening"
      name: "Lost & Found"
      url: "/lostandfound"
    - id: "assetrental"
      name: "Asset Rental"
      url: "/assetrental"
    - id: "ba_line"
      name: "BA Line"
      url: "/ba_line"
 - id: "contact"
   name: "Contact Us"
   url: "/contact"
   lines: 1
 - id: "search"
   name: "Search"
   url: "/search" #url: "/archive"
   lines: 1
   sub:
    - id: "searchbar"
      name: "(search bar goes here)"
      url: "/" #url: "/2015"


address:
 - ""
 - ""
 - ""
mail: ""
urlOfficial: "http://"
urlFacebook: "https://"
#urlTwitter: "https://"
#urlInstagram: "https://"
#urlYouTube: "https://"
#urlSnapchat: "https://"
#urlViber: "http://"
