# Site settings

title: "QC International Pink Film Festival 2016"
baseurl: http://toffmendoza.me/sandbox-qcpinkfest
#baseurl: http://qcpinkfest.com

# Build settings
markdown: kramdown
permalink: pretty

# Site variables


itemsNavbarLeft:
 - id: "about"
   name: "About"
   url: "/" #url: "/about"
 - id: "program"
   name: "Program"
   url: "/" #url: "/program"
   sub:
    - id: "opening"
      name: "Opening"
      url: "/opening"
    - id: "keps"
      name: "Keps"
      url: "/keps"
 - id: "films"
   name: "Films"
   url: "/films"
   sub:
    - id: "trailers"
      name: "Trailers"
      url: "/trailers"
    - id: "schedule"
      name: "Schedule"
      url: "/schedule"
    - id: "tickets"
      name: "Tickets"
      url: "/tickets"
itemsNavbarRight:
 - id: "news"
   name: "News"
   url: "/" #url: "/news"
 - id: "contact"
   name: "Contact"
   url: "/contact"
 - id: "archive"
   name: "Archive"
   url: "/" #url: "/archive"
   sub:
    - id: "2015"
      name: "2015"
      url: "/2015"
    - id: "2014"
      name: "2014"
      url: "/2014"


itemsSponsors:
 - id: ""
   name: ""
   logo: ""
 - id: ""
   name: ""
   logo: ""
 - id: ""
   name: ""
   logo: ""


films:
 - id: "love-out-loud"
   name: "Love Out Loud"
   director: "Gilb Mendoza"
   image: "filler-640x480-1.jpg"
   category: "Comedy"
   runtimeMins: "120"
   schedule:
    - date: "December 1"
      venue: "Gateway Cinema 1"
      time:
       - "2PM"
       - "4PM"
       - "6PM"
       - "8PM"
   plot: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi."
 - id: "kaba"
   name: "Kaba"
   director: "Adrian Maquilan"
   image: "filler-640x480-2.jpg"
   category: "Thriller"
   runtimeMins: "120"
   schedule:
    - date: "December 2"
      venue: "Gateway Cinema 2"
      time:
       - "2PM"
       - "4PM"
       - "6PM"
       - "8PM"
   plot: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi."


address:
 - "#605 Sterten,"
 - "Maginhawa St., Diliman"
 - "1101 Quezon City, Metro Manila"
mail: "qcpinkfilmfest@gmail.com"
urlOfficial: "http://qcpinkfest.com/"
urlFacebook: "https://www.facebook.com/qcpinkfest/"
#urlTwitter: "https://twitter.com/y4it"
#urlInstagram: "https://www.instagram.com/y4it/"
#urlYouTube: "https://www.youtube.com/user/iloveY4iT"
#urlSnapchat: "https://www.snapchat.com/add/y4it"
#urlViber: "http://chats.viber.com/y4it"
