# Site settings
title: Y4iT
baseurl: http://toffmendoza.me/sandbox-y4it
#baseurl: http://y4it.org


# Build settings
markdown: kramdown
permalink: pretty
# baseurl:

# Site variables
switchAnnouncement: false
switchSpeakers: true
switchSpeakersHeader: false
switchParallel: false
switchPayment: false
switchFAQ: true
switchSponsor: true
switchPartners: true
switchTerms: true

switchFooterSitemap: false


speakers:
 - id: "jdeluzuriaga"
   name: "Jonathan Defensor De Luzuriaga"
   image: "De_Luzuriaga_Jonathan-edit-web.jpg"
   professional:
    - designation: "President"
      company: "Philippine Software Industry Association"
    - designation: "Founder and Chief Executive Officer"
      company: "CMI Tech"
   description: "As the President of the Philippine Software Industry Association, Jonathan leads the way for the Information Technology industry of the Philippines. He is also the Founder and CEO of CMI Tech, a software innovations company involved in developments in web, mobile and cloud solutions for various verticals. Jonathan is a seasoned independent World Bank Consultant for global information technology initiatives responsible for the design and implementation of such projects as the Center of Excellence in IT-BPO for Central Africa, the feasibility study of the Malili Technopark in Kenya as well as a multitude of talent mapping initiatives in Southeast Asia. He has been invited in numerous occasions to lecture about outsourcing and offshoring in various events and conferences in all parts of the world. He is known simply as JDL within the different sectors of business processing, information technology and innovation sectors. He holds a Political Science degree from the De La Salle University."
   social:
    - type: ""
      url: ""
 - id: "psmithson"
   name: "Phil Smithson"
   image: "Smithson_Phil1-edit-web.jpg"
   professional:
    - designation: "Lead Service Designer and Director"
      company: "On-Off Group"
   description: "Phil is a Lead Service Designer and Director of On-Off Group. He's been helping companies design experiences for over 10 years and has taught UX to over 1,500 people. In 2015, he spent 3 months travelling the Philippines introducing UX to multiple universities. He finds it difficult to switch off the 'designer' part of his brain and is always thinking about how to improve experiences wherever he goes."
   social:
    - type: ""
      url: ""
 - id: "msantos"
   name: "Mary Grace Mirandilla-Santos"
   image: "Mirandilla-Santos_Grace-edit-web.jpg"
   professional:
    - designation: "Vice President for Policy"
      company: "Internet Society Philippines Chapter"
   description: "She is an independent researcher specializing in telecommunications and information and communications technology (ICT) policy, and technology’s impact on development and society. Her areas of interest include telecom/ICT regulation and competition policy, e-government, e-democracy, and universal ICT access. Currently, she is a national ICT research consultant at the Asian Development Bank and a local expert for a European Union-funded research project on telecommunications competition mapping. Her personal advocacy is better telecom and Internet services in the Philippines. She is a research fellow of LIRNEasia, a regional ICT policy think tank, and vice president for policy of the Internet Society (ISOC) Philippine Chapter."
   social:
    - type: ""
      url: ""
 - id: "mwarren"
   name: "Miguel Warren"
   image: "Warren_Miguel-edit-web.jpg"
   professional:
    - designation: "Country Manager"
      company: "Payoneer"
   description:
    - "Miguel is the Country Manager of Payoneer Philippines, a leading cross-border payments company for small businesses and professionals worldwide. Founded in 2005 and based in New York, Payoneer is venture-backed, profitable and ranked in the top 100 of Inc. 5000’s Financial Services companies. Miguel has been involved in financial services technology since 2003 with global solution providers such as FIS, SunGard and GFG Group (now Wirecard). He has worked with banks, mobile payment operators and payment schemes (Visa, Mastercard, UnionPay) across South East Asia to deliver card, mobile and cross border payment solutions for consumer and business-to-business (B2B) payments."
    - "Miguel graduated from Ateneo De Manila University with a Bachelor of Science in Management Engineering."
   social:
    - type: ""
      url: ""
 - id: "jchen"
   name: "Joyce Chen"
   image: "Chen_Joyce-edit-web.jpg"
   professional:
    - designation: "GSE Strategy & Development Senior Manager"
      company: "ICANN"
   description: "Joyce joined ICANN staff on February 2016. She currently serves the organization as GSE Strategy and Development Senior Manager in the Asia Pacific APAC Hub based in Singapore. Her main focus will be in deepening ICANN’s engagement within Southeast Asia and other countries in the APAC region. She previously worked in Singapore Institute of Technology for Corporate Communications as well as Strategic Planning. Joyce has experience in corporate development strategies and media relations. Joyce was also a young diplomat with Singapore’s Ministry of Foreign Affairs upon graduating from National University of Singapore. She handled the ASEAN portfolio while in the Foreign Affairs."
   social:
    - type: ""
      url: ""
 - id: "mibrahim"
   name: "Monchito Ibrahim"
   image: "Ibrahim_Monchito-edit-web.jpg"
   professional:
    - designation: "Consultant for eInnovation"
      company: "Department of Information & Communications Technology"
    - designation: "President"
      company: "UP System IT Foundation, Inc."
   description:
    - "Currently with the Department of Information and Communications Technology (DICT) as Consultant for eInnovation, he served as Commissioner of the former Commission on Information and Communications Technology (CICT) from 2007 until 2011."
    - "In the course of his extensive involvement in the IT industry, he has worked for multinational companies like Fujitsu, WeServ, Siemens-Nixdorf, Comparex Germany and Unisys Australia in various executive positions. During the 2012 International ICT Awards organized by the Canadian Chamber of Commerce of the Philippines, he was given the ICT Individual Contributor Award for his contributions to the growth of the Philippine IT-BPO Industry. He was also recently named as one of the Ten ICT Industry Movers and Shakers for the period 2002-2012 and recipient of the Boards’ Choice as Government Champion, both given by the Contact Center Association of the Philippines (CCAP)."
   social:
    - type: ""
      url: ""
 - id: "shermoso"
   name: "Sheryl Hermoso"
   image: "Hermoso_Sheryl-edit-web.jpg"
   professional:
    - designation: "Senior Training Officer"
      company: "Asia-Pacific Network Information Centre (APNIC)"
   description:
    - "Sheryl has had various roles as Network and Systems Administrator before joining the Asia Pacific Network Information Centre (APNIC). She started her career as a Technical Support Assistant while studying at the University of the Philippines."
    - "She later finished her degree in BS Computer Engineering and continued to work in the same University as a Network Engineer, where she managed the Diliman Network (DilNet) backbone and wireless infrastructure."
    - "Her areas of interest include wireless and Wi-Fi technologies, DNS/DNSSEC, IPv6, and network security concerns, among others."
   social:
    - type: ""
      url: ""
 - id: "jjanssens"
   name: "Johan Janssens"
   image: "Janssens_Johan-edit-web.jpg"
   professional:
    - designation: "Chief Innovator"
      company: "Timble"
   description: "Johan is a Belgian web architect, tech entrepreneur and free software advocate. In the past 10 years Johan has spent most his time creating and advocating free and open source software and helping evolve the world wide web. Johan is most known as co-founder and lead developer of Joomla, an open source content management system used by more than 3% of all the sites on the internet. Johan is passionate about creating software architectures that help other developers get things done faster. Today, Johan spends most of his time helping governments and large organisations implementing open data web solutions using open source technologies. Johan is Director of Timble and founder of Joomlatools and Wordplugs. Johan is a firm believer in sharing and collaboration, in spreading good ideas and in the power of technology to make the world a better place. He continually pushes the people around him to be creative and connect the dots."
   social:
    - type: ""
      url: ""
 - id: "pgioca"
   name: "Philip Gioca"
   image: "Gioca_Philip-edit-web.jpg"
   professional:
    - designation: "Country Manager"
      company: "Jobstreet.com Philippines"
   description: "As Jobstreet.com Philippines’s top executive, Philip is responsible for the overall strategy and execution for the company’s online recruitment services in the Philippines. Prior to his installation in his new role earlier this year, he was the company&apos;s Director for Sales, where he managed and grew sales through broad organizational developments, marketing strategies, and leadership. He spearheaded various sales teams to be in a market leading position. Prior to his years in JobStreet.com, he had been a part of the executive committee of the leading multinational insurance company in the country. He graduated with a degree of BS Management in Ateneo de Manila University."
   social:
    - type: ""
      url: ""
 - id: "hduh"
   name: "Henry Duh"
   image: "Duh_Henry-edit-web.jpg"
   special:
    - display: "ACM"
      title: "ACM Distinguished Speaker"
   professional:
    - designation: "Director"
      company: "Human Interface Technology Laboratory Australia"
   description: "Professor Duh is the Director of Human Interface Technology Laboratory Australia and Professor of School of Engineering & ICT at University of Tasmania. He is a Fellow of the Institution of Engineering and Technology and British Computer Society, ACM Distinguished Speaker; the Australian National Representative of IFIP TC on HCI and Entertainment Computing; Steering committee chair of ChineseCHI and steering committee member of IEEE ISMAR. He is the Editor-in-Chief, Journal of Visual Languages and Computing (Springer), editorial board members of HCI book series (Springer), and published more than 120 conference and journal papers in HCI area. Professor Duh has served the program/organizing committee for IEEE/ACM International Symposium of Mixed and Augmented Reality (ISMAR) and IEEE Virtual Reality for years. His research focuses on augmented/virtual reality, user experience and interaction design, and gaming effects in mobile systems."
   social:
    - type: ""
      url: ""




speakersLegacy:
 - id: "caragon"
   name: "Claudine Aragon"
   image: "Aragon_Claudine-edit-web.jpg"
   professional:
    - designation: "Country Marketing Director"
      company: "Open Garden"
   description: "Claudine is the country marketing director of Open Garden, makers of FireChat - a mobile messaging app that works even without signal or internet connection. Passionate about the intersection of business, marketing, and technology, Claudine has immersed herself in the digital space --- from working on e-commerce to peer-to-peer mesh network technology. She recently relocated back to Manila from Hong Kong to lead the growth and adoption of FireChat in the Philippines. She is a magna cum laude graduate of the University of the Philippines with Bachelor of Science degree in Business Administration."
   social:
    - type: ""
      url: ""



schedules:
 - morning:
    - id: "jcruz1"
      topic: "Topic One"
    - id: "jcruz2"
      topic: "Topic Two"
   noon:
    - id: "jcruz3"
      topic: "Topic Three"
    - id: "jcruz4"
      topic: "Topic Four"
 - morning:
    - id: "jcruz5"
      topic: "Topic Five"
    - id: "jcruz6"
      topic: "Topic Six"
   noon:
    - id: "jcruz2"
      topic: "Topic Seven"
    - id: "jcruz4"
      topic: "Topic Eight"
 - morning:
    - id: "jcruz6"
      topic: "Topic Nine"
    - id: "jcruz1"
      topic: "Topic Ten"
   noon:
    - id: "jcruz3"
      topic: "Topic Eleven"
    - id: "jcruz5"
      topic: "Topic Twelve"


parallels:
 - id: "paloalto"
   name: "Computer Security"
   image: ""
   description: "Lorem ipsum"
   profile: ""
   speaker: "Speaker Name"
   designation: ""
   company: "Paloalto"
   social:
    - type: ""
      url: ""
    - type: ""
      url: ""
    - type: ""
      url: ""
 - id: "onoffgroup"
   name: "User Experience Design"
   image: ""
   description: "Lorem ipsum"
   profile: ""
   speaker: "Speaker Name"
   designation: ""
   company: "Paloalto"
   social:
    - type: ""
      url: ""
    - type: ""
      url: ""
    - type: ""
      url: ""
 - id: "microsoft"
   name: "Internet of Things"
   image: ""
   description: "Lorem ipsum"
   profile: ""
   speaker: "Speaker Name"
   designation: ""
   company: "Paloalto"
   social:
    - type: ""
      url: ""
    - type: ""
      url: ""
    - type: ""
      url: ""


sponsors:
 - id: "cdu"
   name: "Cosmic Digital Universe"
   logo: "logo_sponsor-cdu.png"
 - id: "cognizant"
   name: "Cognizant"
   logo: "logo_sponsor-cognizant.png"
 - id: "jobstreet"
   name: "Jobstreet"
   logo: "logo_sponsor-jobstreet.png"
 - id: "payoneer"
   name: "Payoneer"
   logo: "logo_sponsor-payoneer.png"
 - id: "piktochart"
   name: "Piktochart"
   logo: "logo_sponsor-piktochart.png"
 - id: "teradoor"
   name: "Teradoor"
   logo: "logo_sponsor-teradoor.png"



media:
 - id: "anc"
   name: "ABS-CBN News Channel (ANC)"
   logo: "logo_media-anc.png"
 - id: "bworld"
   name: "Business World"
   logo: "logo_media-bworld.png"
 - id: "manilabulletin"
   name: "Manila Bulletin"
   logo: "logo_media-manilabulletin.png"
 - id: "scoutmag"
   name: "Scout Magazine"
   logo: "logo_media-scoutmag.png"
 - id: "speedmag"
   name: "Speed Magazine"
   logo: "logo_media-speedmag.png"



inclusions:
 - name: "Admission"
   description:
    - "<strong>"
    - "Entrance to the Y4iT Plenary and Exhibit Halls."
    - "</>"
    - "You will be granted access to talks of IT experts and booths and activities of Y4iT partners."
 - name: "Congress Kit"
   description:
    - "<strong>"
    - "The official Y4iT Congress Kit."
    - "</>"
    - "This includes AM and PM snacks, souvenir program, and many more freebies from us and from our sponsors!"
 - name: "Certificate"
   description:
    - "<strong>"
    - "Certificate of Participation for each congress day."
    - "</>"
    - "This shall serve as proof of your attendance and participation in this year’s Y4iT."


faqs:
 - question: "Who can attend the event?"
   answer: "Y4iT is mostly attended by IT students, professionals, and enthusiasts, but of course, everyone is invited to join."
 - question: "How do I register for the event?"
   answer: "To register online, go to reg2016.y4it.org and follow the steps provided. To register on-site, just go to the registration booth, provide the Secretariat with necessary information, and pay for the total registration fee."
 - question: "Can I register online and pay on-site (during event day)?"
   answer: "Yes, you may accomplish the registration form online and pay during event day. However, badge rates depend on the date of purchase and not of registration. Payments made during the event day will follow the walk-in rate."
 - question: "Can I register online and pay offsite (direct payment at UPSITF office or bank deposit) but claim my badge/s on-site?"
   answer: "Yes, you may claim your badge/s on-site or during the event when you register online and pay before the event. Just present the Registration Summary and proof of payment."
 - question: "Why should we register online?"
   answer: "Those who register online will be prioritized during the event. On-site registrants (walk-in participants) will only be accommodated at 9am."
 - question: "I failed to bring or print out my Registration Summary. Would I still be able to claim my badges?"
   answer: "Yes. Just bring proof of payment to claim your badges."
 - question: "I lost my badge, would the management still be able to replace it?"
   answer: "Unfortunately, Y4iT will not replace lost badge/s."
 - question: "How long will the program be?"
   answer: "Gates open at 7am. The program starts at 9am and ends at 4pm."
 - question: "Will there be different programs per day?"
   answer: "Yes, there will be a different program for each day. Expect to learn and be inspired by different speakers and topics each day."


terms:
 - name: "Refund"
   description: "Tickets are non-refundable but transferrable."
 - name: "Speakers"
   description: "Y4iT reserves the right to cancel or replace speakers."

organizerDescription:
 - "The UP System Information Technology Foundation (UPSITF) Inc. is a non-government organization focused on the application of Information and Communication Technology for development. It partners with UP Information Technology Development Center in providing various services such as, but not limited to, Education Development, IT Human Capital Development, Research &amp; Development, Software Engineering, ICT Policy Development and Planning, and IT Project Management."
